# Uncomment the next line to define a global platform for your project
platform :ios, 9.0

target 'ASRoam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ASRoam
  pod 'RealmSwift'
  pod 'RAMAnimatedTabBarController', "~> 2.0.13"
  pod 'FoldingCell', '~> 2.0.3'
  pod 'expanding-collection', '~> 1.0.3'
  pod 'Alamofire', '~> 4.4'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
